name: volshebnikmedia
favicon: null
layout_spectrum: 0.64453
typography_spectrum: 0.8579626341816038
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1a20'
    - '#142d36'
    - '#859398'
    - '#a5afb3'
    - '#41565e'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.39953087200410664
purpose: []
